import type { HotlistEntry } from "@cloudsourcehrm/db/schema";

const COLUMN_LABELS: Record<string, string> = {
  name: "Name",
  title: "Title",
  skills: "Skills",
  location: "Location",
  work_authorization: "Work Authorization",
  availability: "Availability",
  rate_salary: "Rate / Salary",
  profile_summary: "Summary",
  contact: "Contact",
};

export function renderHotlistTable(
  entries: HotlistEntry[],
  visibleColumns: string[]
): string {
  const cols = visibleColumns.filter((c) => COLUMN_LABELS[c]);

  const headerRow = cols
    .map((c) => `<th style="background:#1B4F8A;color:white;padding:10px 14px;text-align:left;font-size:13px;white-space:nowrap;">${COLUMN_LABELS[c]}</th>`)
    .join("");

  const dataRows = entries
    .map((entry, i) => {
      const bg = i % 2 === 0 ? "#ffffff" : "#f5f8fc";
      const cells = cols.map((col) => {
        let value = "";
        switch (col) {
          case "name":
            value = entry.displayName ?? "";
            break;
          case "title":
            value = entry.title ?? "";
            break;
          case "skills":
            value = (entry.skills ?? []).join(", ");
            break;
          case "location":
            value = [entry.city, entry.state].filter(Boolean).join(", ");
            break;
          case "work_authorization":
            value = entry.workAuthorization ?? "";
            break;
          case "availability":
            value = entry.availability ?? "";
            break;
          case "rate_salary":
            value = entry.rateSalary ?? "";
            break;
          case "profile_summary":
            value = entry.profileSummary ?? "";
            break;
          case "contact":
            value = [entry.contactEmail, entry.contactPhone].filter(Boolean).join(" | ");
            break;
        }
        return `<td style="padding:10px 14px;border-bottom:1px solid #e5e7eb;font-size:13px;color:#1a1a2e;">${escapeHtml(value)}</td>`;
      });
      return `<tr style="background:${bg};">${cells.join("")}</tr>`;
    })
    .join("");

  return `
    <div style="font-family:Arial,sans-serif;margin:20px 0;">
      <table style="border-collapse:collapse;width:100%;min-width:600px;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden;">
        <thead>
          <tr>${headerRow}</tr>
        </thead>
        <tbody>
          ${dataRows}
        </tbody>
      </table>
      <p style="font-size:11px;color:#9ca3af;margin-top:8px;">
        Generated by CloudSourceHRM &mdash; Confidential
      </p>
    </div>
  `.trim();
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
